merge_queue:
  max_parallel_checks: 1
queue_rules:
  - name: default
    batch_size: 1
    queue_conditions:
      - base=main
      - or:
          - "#approved-reviews-by>=1"
          - author=jacobweinstock
      - "#changes-requested-reviews-by=0"
      - check-success=DCO
      - check-success=build-initramfs (amd64)
      - check-success=build-initramfs (arm64)
      - check-success=build-kernel (amd64)
      - check-success=build-kernel (arm64)
      - check-success=download-tools (amd64)
      - check-success=download-tools (arm64)
      - check-success=build-iso (amd64)
      - check-success=build-iso (arm64)
      - label!=do-not-merge
      - label=ready-to-merge
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - base=main
      - or:
          - "#approved-reviews-by>=1"
          - author=jacobweinstock
      - "#changes-requested-reviews-by=0"
      - check-success=DCO
      - check-success=build-initramfs (amd64)
      - check-success=build-initramfs (arm64)
      - check-success=build-kernel (amd64)
      - check-success=build-kernel (arm64)
      - check-success=download-tools (amd64)
      - check-success=download-tools (arm64)
      - check-success=build-iso (amd64)
      - check-success=build-iso (arm64)
      - label!=do-not-merge
      - label=ready-to-merge
      # This extra condition forces draft PR mode (prevents in-place checks)
      - queue-position>=0
    merge_method: merge
    commit_message_template: |
      {{ title }} (#{{ number }})

      {{ body }}

pull_request_rules:
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
